"""add scoresheet_data_path to leagues

Revision ID: fcd42b502fd3
Revises: 68676888b6aa
Create Date: 2026-02-23 12:16:21.796118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd42b502fd3'
down_revision: Union[str, None] = '68676888b6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('scoresheet_data_path', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('players_scoresheet_id_key'), 'players', type_='unique')
    op.drop_index(op.f('ix_players_scoresheet_id'), table_name='players')
    op.create_index(op.f('ix_players_scoresheet_id'), 'players', ['scoresheet_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_players_scoresheet_id'), table_name='players')
    op.create_index(op.f('ix_players_scoresheet_id'), 'players', ['scoresheet_id'], unique=False)
    op.create_unique_constraint(op.f('players_scoresheet_id_key'), 'players', ['scoresheet_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('leagues', 'scoresheet_data_path')
    # ### end Alembic commands ###
